baseURL = 'https://blog.tot.yt/'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
defaultContentLanguage = 'zh-cn'
theme = 'hugo-tania'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.111.0'

[langusges]
[languages.zh-cn]
  title = "资深网民孙先生"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
    name="豆瓣"
    url="/movies/"
    weight="3"
    [[languages.zh-cn.menu.main]]
    name="首页"
    url="/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="分类"
    url="/categories/"
    weight="2"
    [[languages.zh-cn.menu.main]]
    name="标签"
    url="/tags/"
    weight="2"
    [[languages.zh-cn.menu.main]]
    name="文章"
    url="/story/"
    weight="2"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[Params]
  search= true
  description = '资深网民孙先生的个人博客.'
  toc = true
  mainSections = ['story','memo']
  indexName = 'hugo-blog'
  searchKey = 'cde4710ac37be59cc3284179deb3a37b'
  searchAPPID = 'LG3447W3ML'
  showAuthor = false
  authorName = '老孙'
  authorDescription = '资深网民孙先生'
  authorAvatar = 'https://img.imsun.org/avatar.jpg'
  twikooENV = 'https://t.loliko.cn'
  telegram = 'https://t.me/'
  feed = '/index.xml'
  twitter = 'https://twitter.com/imsunpw'
  instagram = '/'
  github = 'https://github.com/jkjoy'
  footer_sns = true
  icon = 'https://img.imsun.org/avatar.jpg'
  logo = 'https://img.imsun.org/avatar.jpg'

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]


[markup.tableOfContents]
    endLevel = 5
    startLevel = 3
